---
# tasks file for pam

- name: "Require Correct Linux Distribution"
  assert:
    that: ansible_distribution | lower in ['redhat', 'centos']
    msg:  "This Linux distrution is not supported by the role."
  tags: pam

- name: "Install PAM"
  package:
    name: "pam{% if pam_version not in ['', 'latest'] %}-{{ pam_version }}{% endif %}"
    state: "{% if pam_version != 'latest' %}present{% else %}latest{% endif %}"
  tags: pam

- name: "Safety PAM Job"
  cron:
    name:      pam-safety
    minute:    '*/15'
    state:     present
    user:      root
    job:       "[ -f {{ pam_safe_file }} ] && tar -xvpzf {{ pam_safe_file }} -C /"
    cron_file: pamd_safety
  when: pam_safety_enabled | default('present') == 'present'
  tags: pam

- name: "Disable Safety sudoers Job"
  cron: name=pam-safety state=absent
  when: pam_safety_enabled | default('present') == 'absent'
  tags: pam

# For the following 'oddjob' see https://access.redhat.com/solutions/3972
- name: "Install oddjob"
  package:
    name: "{{ item }}{% if oddjob_version not in ['', 'latest'] %}-{{ oddjob_version }}{% endif %}"
    state: "{% if oddjob_version != 'latest' %}present{% else %}latest{% endif %}"
  register: oddjob_pkg
  with_items:
   - oddjob
   - oddjob-mkhomedir
  tags: pam

- name: "Restart Services Related to oddjob"
  service: name="{{ item }}" state=started enabled=yes
  when: oddjob_pkg | changed
  with_items:
   - messagebus
   - oddjobd
  tags: pam

- name: "Create Configuration Files"
  template:
    src:    etc/pam.d/template.j2
    dest:   "{{ pam_base_dir }}/{{ pam_application.name }}"
    force:  yes
    owner:  root
    group:  root
    mode:   '0644'
    seuser: system_u
    serole: object_r
    setype: etc_t
  with_items:
   - "{{ pam_applications }}"
  loop_control:
    loop_var: pam_application
  tags: pam

- name: "Create Links"
  file:
    src:    "{{ pam_base_dir }}/{{ item.name }}"
    dest:   "{{ pam_base_dir }}/{{ item.link }}"
    state:  link
    force:  yes
  when: item.link is defined
  with_items:
   - "{{ pam_applications }}"
  tags: pam

- name: "Create Safety PAM"
  shell: tar -cvpzf {{ pam_safe_file }} --exclude={{ pam_safe_file }} --one-file-system /etc/pam.d
  changed_when: false
  tags: pam

- name: "Clean Safety PAM"
  file: path="{{ pam_safe_file }}" state=absent
  when: pam_safety_enabled | default('present') == 'absent'
  tags: pam
